#!/bin/bash
set -euo pipefail

# Generate the ask-ben routing table from .claude-plugin/plugin.json + each
# skill's SKILL.md frontmatter. Kills the hand-maintained catalog copy: rows
# can no longer drift from the skills on disk.
#
# Usage: scripts/generate-skill-catalog.sh [--check]
#   (no args)  rewrite the table block in ask-ben/SKILL.md
#   --check    exit 1 if the table differs from what would be generated

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
MODE="${1:-apply}"

python3 - "$REPO_ROOT" "$MODE" <<'PY'
import json, pathlib, re, sys

repo = pathlib.Path(sys.argv[1])
mode = sys.argv[2]

skills = json.loads((repo / ".claude-plugin/plugin.json").read_text())["skills"]

rows = []
for entry in sorted(skills):
    d = entry.strip("./")
    p = repo / d / "SKILL.md"
    if not p.exists():
        print(f"MISSING SKILL.md for registered skill: {d}", file=sys.stderr)
        sys.exit(1)
    text = p.read_text()
    m = re.match(r"---\n(.*?)\n---", text, re.S)
    fm = m.group(1) if m else ""
    name = re.search(r"^name:\s*(.+)$", fm, re.M)
    desc = re.search(r"^description:\s*(.+)$", fm, re.M)
    name = name.group(1).strip().strip('"') if name else d
    desc = desc.group(1).strip().strip('"') if desc else ""
    # first sentence, trimmed for the table
    first = re.split(r"(?<=[.!?]) ", desc)[0].strip()
    if len(first) > 110:
        first = first[:107].rstrip() + "..."
    rows.append(f"| `/{name}` | {first} |")

table = "\n".join(rows)

askben = repo / "ask-ben/SKILL.md"
s = askben.read_text()
START = "<!-- catalog:start (generated by scripts/generate-skill-catalog.sh -- do not edit rows by hand) -->"
END = "<!-- catalog:end -->"

block = f"{START}\n| Skill | Use for |\n|---|---|\n{table}\n{END}"

if START in s:
    new = re.sub(re.escape(START) + r".*?" + re.escape(END), block, s, flags=re.S)
else:
    # first generation: replace the existing contiguous table (header + rows)
    new = re.sub(r"\| Skill \| Use for \|\n\|---\|---\|\n(\| `/.*\|\n?)+", block + "\n", s)
    if START not in new:
        # no recognizable table header: replace the bare row block
        new = re.sub(r"(\| `/.*\|\n?)+", block + "\n", s, count=1)

if mode == "--check":
    if new != s:
        print("DRIFT: ask-ben catalog table differs from generated output. Run scripts/generate-skill-catalog.sh", file=sys.stderr)
        sys.exit(1)
    print("OK: ask-ben catalog matches generated output")
else:
    askben.write_text(new)
    print(f"ask-ben catalog regenerated: {len(rows)} rows")
PY
